### ISSUE TITLE
[FEATURE] Support `$NO_COLOR` environment variable having an effect.

### ISSUE THREAD

**Issue by Enderchief** [trag1c/Dahlia#2]
**Is your feature request related to a problem? Please describe.**
I use a programming language named Samarium and run it sometimes in a web environment. It would be useful if I could disable the colouring directly from Dahlia as ansi escapes don't show up well on the web.
I suggest a way to disable colouring.

**Describe the solution you'd like**
Detection of if the environment variable `$NO_COLOR` is set. If it is, all text should be returned without formatting.

**Describe alternatives you've considered**
Currently I just use regex to remove it but that is not convenient and slow.

**Additional context**
https://no-color.org/

**Comment by trag1c** [comment]
Added in [0.2.0](https://github.com/trag1c/Dahlia/releases/tag/2.0.0)
