### ISSUE TITLE
Move `master` branch to `main`

### ISSUE THREAD

**Issue by qexat** [trag1c/Dahlia#5]

**Comment by trag1c** [comment]
> most of GitHub repos have moved from `master` branch to `main`
1. most GitHub repos* :nerd_face:
2. it's just that GitHub changed the default, I don't think most of them actually moved

also I have it set to `master` explicitly ¯\\\_(ツ)_/¯
<img width="401" alt="image" src="https://user-images.githubusercontent.com/77130613/194722817-7d1a2cff-1058-46a5-82e1-f4a622645449.png">

I might use `main` in the future but rn I simply prefer `master`

**Comment by qexat** [comment]
bruh
