### ISSUE TITLE
[FEATURE] Support for bedrock color style

### ISSUE THREAD

**Issue by Sigmanificient** [trag1c/Dahlia#6]
**Is your feature request related to a problem? Please describe.**
I notice that the character `&` is used as the marker for color formatting. 
Minecraft bedrock edition uses `§` as the marker as i believer this would be a nice to have, or even support for a custom character as a parameter.

![image](https://user-images.githubusercontent.com/53050011/197173537-5f35ac09-12a1-4cf1-b9e3-67b68e262cba.png)

**Describe the solution you'd like**
I suggest to have a `marker` flag or something that kind:
```py
# defaults to: d = Dahlia(marker_style=Dahlia.marker.JAVA)
d = Dahlia(marker_style=Dahlia.marker.BEDROCK)
```
or with a custom marker:
```py
d = Dahlia(marker='!')
```

**Comment by trag1c** [comment]
Both Java and Bedrock Edition use `§`, it's just that older Java Edition versions (and most server plugins) used `&`. 

I was considering `§` during development but thought that `§` is harder to type on most keyboards + `&` is the one I used more back when playing the game a lot, so it is closer to my heart in some way.

I will reconsider this though.

**Comment by trag1c** [comment]
Added in Dahlia 2.1.0, thanks!
