### ISSUE TITLE
[CODE] Splitting in smaller files for organization

### ISSUE THREAD

**Issue by Sigmanificient** [trag1c/Dahlia#8]
The current `dahlia.py` file is only about 400 lines of code but it is always nice to split code into small dedicated files.
Hence I propose something like the following:

- `constants.py` for storing all the constants, especially the color maps that take up a lot of space
- `legacy.py` for `dprint` & `dahlia` legacy functions
- maybe a `utils.py` to keep only the `Dahlia` class into `dahlia.py`?

**Comment by trag1c** [comment]
Implemented already, thanks!
